---
- name: Install XUI with SSL
  hosts: all
  become: yes
  vars:
    panel_domain: "{{xui_domain}}"
    panel_username: "admin"
    panel_password: "{{xui_password}}"
    panel_port: "5678"
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes

    - name: Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: yes
      become: yes

    - name: Run the Bash Command
      expect:
        command: "sh -c 'curl -o install.sh https://raw.githubusercontent.com/alireza0/x-ui/master/install.sh && chmod +x install.sh && ./install.sh'"

        responses:
          "Do you want to continue with the modification \\[y/n\\]\\? :.*": "y"
          'Please set up your username:': '{{ panel_username }}'
          'Please set up your password:': '{{ panel_password }}'
          'Please set up the panel port:': '{{ panel_port }}'
      register: script_output
      changed_when: false
      ignore_errors: yes
      timeout: 1000  # Set the timeout to 1000 seconds (16 minutes)

    - name: Your panel credentials 
      debug:
        msg: "IMPORTANT  ##### PANEL URL >>  {{panel_domain}}:{{panel_port}} ####>> Username: admin ####>> Password: {{ panel_password }}"
    
    - name: SSL Ensure snapd is installed
      apt:
        name: snapd
        state: present
        update_cache: yes
    # - name: Debug script output
    #   debug:
    #     var: script_output.stdout_lines

    - name: SSL- Install core via Snap
      shell: "snap install core; snap refresh core"

    - name: SSL- Install Certbot via Snap (Classic)
      shell: "snap install --classic certbot"

    - name: SSL- Create Symbolic Link for Certbot
      file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
        force: yes


    - name: SSL- Obtain Let's Encrypt SSL Certificate
      shell: "certbot certonly --standalone --register-unsafely-without-email --non-interactive --agree-tos -d {{ panel_domain }}"

    - name: #### Panel password
      debug:
        msg: "IMPORTANT  ##### PANEL URL >>  {{panel_domain}}:{{panel_port}} ####>> Username: admin ####>> Password: {{ panel_password }} |####"

    - name: #### SSL certificate
      debug:
        msg: "IMPORTANT ##### Copy this to your panel settings to setup the SSL certificate (HTTPS) ####> Public Key File Path: /etc/letsencrypt/live/{{panel_domain}}/cert.pem ####> Private Key File Path: /etc/letsencrypt/live/{{panel_domain}}/privkey.pem  |####"

